name: NodeJS and nexe

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm Build
      run: |
        npm install
        
    - name: tsc build
      run: |
        tsc
        
    - name: nexe build
      run: |
        npx nexe -i ./out/mapping-generator.js --verbose --build
        
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: mapping-generator*
      
